# from rnaturalearth
language: r
warnings_are_errors: true
sudo: required
cache: packages

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
        - os: linux
          r: devel
          dist: trusty

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev libnetcdf-dev

r_packages:
  - devtools
  - ncdf4

notifications:
  email:
    on_success: change
    on_failure: change