sudo: required
dist: trusty
group: deprecated-2017Q4 # fallback to old version, which works

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev libnetcdf-dev

language: r
cache: packages

r:
  - release
  - devel

warnings_are_errors: false

r_packages:
- devtools