sudo: required
dist: trusty
group: deprecated-2017Q4

before_install:
  - sudo apt-get install netcdf-bin libnetcdf-dev libgdal1-dev libproj-dev

language: r
cache: packages

r:
  - release
  - devel

warnings_are_errors: false

r_packages:
  - devtools
  - rgdal
