language: R
sudo: required
cache: packages
warnings_are_errors: false

before_install:
    - sudo apt-get install --yes udunits-bin libudunits2-dev
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libgdal1-dev 
    - sudo apt-get install --yes libnetcdf-dev hdf4-tools libnetcdf4 netcdf-bin
r:
  - release
  - devel

r_packages:
  - devtools