language: R
sudo: required
cache: packages
warnings_are_errors: false

before_install:
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev libnetcdf-dev

r:
  - release
  - devel

r_packages:
  - devtools