language: r

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends
                         libgdal1-dev libgeos-dev libproj-dev
